#!/usr/bin/env python3
"""
Generate publication figures for the meta-analysis extraction paper.

Reads validation results from all 5 datasets and produces:
  Figure 1: System architecture (text description -- cannot generate diagram)
  Figure 2: Scatter plots of extracted vs GT effect sizes (5 panels)
  Figure 3: Cross-dataset comparison bar chart (r, MAE, direction)
  Figure 4: Bland-Altman plots (5 panels)
  Figure 5: Source type accuracy comparison (table vs figure)

Usage:
    ./venv/Scripts/python.exe FINAL_SUBMISSION_2026-03-08/generate_figures.py

Saves all figures as PNG to FINAL_SUBMISSION_2026-03-08/figures/
"""

import sys
import os
import json
import warnings

sys.stdout.reconfigure(encoding='utf-8')
warnings.filterwarnings('ignore')

# Resolve paths relative to the reproduction directory (where this script lives)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FIGURES_DIR = os.path.join(SCRIPT_DIR, 'figures')
OUTPUT_DIR = os.path.join(SCRIPT_DIR, 'data')

os.makedirs(FIGURES_DIR, exist_ok=True)

try:
    import numpy as np
    import pandas as pd
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import matplotlib.gridspec as gridspec
    import seaborn as sns
except ImportError as e:
    print(f"Missing dependency: {e}")
    print("Install with: pip install numpy pandas matplotlib seaborn")
    sys.exit(1)

# Set publication style
sns.set_theme(style='whitegrid', font_scale=1.1)
plt.rcParams.update({
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'font.size': 10,
    'axes.titlesize': 11,
    'axes.labelsize': 10,
})

DATASET_COLORS = {
    'Loladze': '#1f77b4',
    'Hui': '#2ca02c',
    'Li': '#ff7f0e',
    'Biochar': '#d62728',
    'Boldorini': '#9467bd',
}

# Standardized display names for figure labels (internal keys remain unchanged)
DISPLAY_NAMES = {
    'Loladze': 'Loladze 2014',
    'Hui': 'Hui 2025',
    'Li': 'Li 2022',
    'Biochar': 'Li 2024 (biochar)',
    'Boldorini': 'Boldorini 2024',
}


# ---------------------------------------------------------------------------
# Data loading helpers
# ---------------------------------------------------------------------------

def load_formal_stats():
    """Load the formal_stats_all_datasets.json file (generated by formal_stats_all_datasets.py)."""
    path = os.path.join(SCRIPT_DIR, 'output', 'formal_stats_all_datasets.json')
    if not os.path.exists(path):
        print(f"WARNING: {path} not found. Some figures will be skipped.")
        return None
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_loladze_matches():
    """Load Loladze validation matches from LLM-aligned JSON."""
    path = os.path.join(OUTPUT_DIR, 'loladze_agent_replication', 'validation_llm_10pp.json')
    if not os.path.exists(path):
        print(f"WARNING: Loladze matches not found at {path}")
        return None
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    matched_obs = data.get('matched_observations', [])
    if not matched_obs:
        print("WARNING: No matched_observations in Loladze validation JSON")
        return None
    rows = []
    for obs in matched_obs:
        ext = obs.get('ext_effect_pct')
        gt = obs.get('gt_effect_pct')
        if ext is not None and gt is not None:
            rows.append({'ext_pct': float(ext), 'gt_pct': float(gt), 'dataset': 'Loladze'})
    if not rows:
        return None
    return pd.DataFrame(rows)


def load_hui_matches():
    """Load Hui validation matches CSV.
    Uses validation_matches_improved.csv (319 obs) which is the same file
    used by formal_stats_all_datasets.py.  Columns: ext_effect, gt_effect
    (percentage-point effect sizes).
    """
    improved_path = os.path.join(OUTPUT_DIR, 'hui2023_full_35', 'validation_matches_improved.csv')
    fallback_path = os.path.join(OUTPUT_DIR, 'hui2023_full_35', 'validation_matches.csv')
    path = improved_path if os.path.exists(improved_path) else fallback_path
    if not os.path.exists(path):
        print(f"WARNING: Hui matches not found at {improved_path}")
        return None
    df = pd.read_csv(path)
    if 'ext_effect' in df.columns and 'gt_effect' in df.columns:
        df['ext_pct'] = df['ext_effect']
        df['gt_pct'] = df['gt_effect']
    else:
        print(f"WARNING: Hui CSV missing expected columns (ext_effect, gt_effect). Found: {list(df.columns)}")
        return None
    df['dataset'] = 'Hui'
    return df[['ext_pct', 'gt_pct', 'dataset']].dropna()


def load_li_matches():
    """Load Li validation matches CSV.
    Uses validation_matches_effect_first.csv (117 obs) which is the same file
    used by formal_stats_all_datasets.py.  Columns: ext_effect_pct, gt_effect_pct.
    """
    path = os.path.join(OUTPUT_DIR, 'li2022_combined', 'validation_matches_effect_first.csv')
    if not os.path.exists(path):
        print(f"WARNING: Li matches not found at {path}")
        return None
    df = pd.read_csv(path)
    if 'gt_effect_pct' in df.columns and 'ext_effect_pct' in df.columns:
        df['ext_pct'] = df['ext_effect_pct']
        df['gt_pct'] = df['gt_effect_pct']
    else:
        print(f"WARNING: Li CSV missing expected columns. Found: {list(df.columns)}")
        return None
    df['dataset'] = 'Li'
    return df[['ext_pct', 'gt_pct', 'dataset']].dropna()


def load_biochar_matches():
    """Load biochar validation data from validation_results.json matched_observations."""
    path = os.path.join(OUTPUT_DIR, 'biochar_extraction', 'validation_results.json')
    if not os.path.exists(path):
        print(f"WARNING: Biochar validation not found at {path}")
        return None
    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        obs = data.get('matched_observations', [])
        if not obs:
            print("WARNING: Biochar validation_results.json has no matched_observations")
            return None
        ext_vals = []
        gt_vals = []
        for m in obs:
            ev = m.get('ext_effect_pct')
            gv = m.get('gt_effect_pct')
            if ev is not None and gv is not None:
                ext_vals.append(float(ev))
                gt_vals.append(float(gv))
        if not ext_vals:
            print("WARNING: No valid paired values in biochar matched_observations")
            return None
        return pd.DataFrame({
            'ext_pct': ext_vals,
            'gt_pct': gt_vals,
            'dataset': 'Biochar'
        })
    except Exception as e:
        print(f"WARNING: Error loading biochar validation: {e}")
        return None


def load_boldorini_matches():
    """Load Boldorini validation data from validation_results.json matched_observations."""
    val_path = os.path.join(OUTPUT_DIR, 'boldorini_extraction', 'validation_results.json')
    if not os.path.exists(val_path):
        print(f"WARNING: Boldorini validation not found at {val_path}")
        return None
    try:
        with open(val_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        obs = data.get('matched_observations', [])
        if not obs:
            print("WARNING: Boldorini validation_results.json has no matched_observations")
            return None
        ext_vals = []
        gt_vals = []
        for m in obs:
            ev = m.get('ext_effect_pct')
            gv = m.get('gt_effect_pct')
            if ev is not None and gv is not None:
                ext_vals.append(float(ev))
                gt_vals.append(float(gv))
        if not ext_vals:
            print("WARNING: No valid paired values in Boldorini matched_observations")
            return None
        return pd.DataFrame({
            'ext_pct': ext_vals,
            'gt_pct': gt_vals,
            'dataset': 'Boldorini'
        })
    except Exception as e:
        print(f"WARNING: Error loading Boldorini validation: {e}")
        return None


def load_all_matches():
    """Load and combine all dataset matches."""
    dfs = []
    loaders = [
        ('Loladze', load_loladze_matches),
        ('Hui', load_hui_matches),
        ('Li', load_li_matches),
        ('Biochar', load_biochar_matches),
        ('Boldorini', load_boldorini_matches),
    ]
    loaded = {}
    for name, loader in loaders:
        try:
            df = loader()
            if df is not None and len(df) > 0:
                dfs.append(df)
                loaded[name] = df
                print(f"  Loaded {name}: {len(df)} observations")
            else:
                print(f"  Skipped {name}: no data")
        except Exception as e:
            print(f"  Error loading {name}: {e}")

    combined = pd.concat(dfs, ignore_index=True) if dfs else None
    return combined, loaded


# ---------------------------------------------------------------------------
# Figure 1: System Architecture (text description)
# ---------------------------------------------------------------------------

def generate_figure1():
    """Generate Figure 1: System architecture diagram as a text-based figure."""
    fig, ax = plt.subplots(figsize=(12, 7))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 7)
    ax.axis('off')
    ax.set_title('Figure 1: System Architecture', fontsize=14, fontweight='bold', pad=20)

    # Draw boxes
    boxes = [
        (1, 5.5, 2, 1, 'PDF\nInputs', '#e8f4fd'),
        (4, 5.5, 2, 1, 'AI Agent\n(Claude Opus 4.6)', '#d4edda'),
        (7, 5.5, 2, 1, 'Structured\nJSON Output', '#fff3cd'),
        (1, 3.5, 2, 1, 'Config\n(PICO, moderators)', '#e8f4fd'),
        (4, 3.5, 2, 1, 'LLM-Driven\nAlignment', '#d4edda'),
        (7, 3.5, 2, 1, 'Matched\nObservations', '#fff3cd'),
        (4, 1.5, 2, 1, 'Statistical\nValidation\n(ICC, TOST, B-A)', '#f8d7da'),
        (7, 1.5, 2, 1, 'Publication\nFigures & Stats', '#fff3cd'),
    ]
    for x, y, w, h, text, color in boxes:
        rect = plt.Rectangle((x, y), w, h, facecolor=color,
                              edgecolor='black', linewidth=1.5, zorder=2)
        ax.add_patch(rect)
        ax.text(x + w/2, y + h/2, text, ha='center', va='center',
                fontsize=9, fontweight='bold', zorder=3)

    # Draw arrows
    arrows = [
        (3, 6, 4, 6),      # PDF -> Agent
        (6, 6, 7, 6),      # Agent -> JSON
        (3, 4, 4, 4),      # Config -> Alignment
        (6, 4, 7, 4),      # Alignment -> Matched
        (5, 5.5, 5, 4.5),  # Agent -> Alignment
        (8, 5.5, 8, 4.5),  # JSON -> Matched
        (5, 3.5, 5, 2.5),  # Alignment -> Validation
        (6, 2, 7, 2),      # Validation -> Figures
    ]
    for x1, y1, x2, y2 in arrows:
        ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                    arrowprops=dict(arrowstyle='->', lw=1.5, color='#333'))

    # Labels
    ax.text(5, 0.5,
            'Reference\nStandards\n(5 datasets)',
            ha='center', va='center', fontsize=9,
            bbox=dict(boxstyle='round,pad=0.3', facecolor='#e2e3e5', edgecolor='black'))
    ax.annotate('', xy=(5, 1.5), xytext=(5, 1.1),
                arrowprops=dict(arrowstyle='->', lw=1.5, color='#333'))

    plt.savefig(os.path.join(FIGURES_DIR, 'figure1_architecture.png'))
    plt.close()
    print("  Saved Figure 1: System architecture")


# ---------------------------------------------------------------------------
# Figure 2: Scatter plots of extracted vs GT effect sizes
# ---------------------------------------------------------------------------

def generate_figure2(loaded_datasets):
    """Generate Figure 2: Scatter plots (one panel per dataset)."""
    datasets = [k for k in ['Loladze', 'Hui', 'Li', 'Biochar', 'Boldorini']
                if k in loaded_datasets]
    n_panels = len(datasets)
    if n_panels == 0:
        print("  Skipping Figure 2: no paired data available")
        return

    cols = min(n_panels, 3)
    rows = (n_panels + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(5 * cols, 5 * rows), squeeze=False)
    fig.suptitle('Figure 2: Extracted vs. Ground-Truth Effect Sizes', fontsize=14,
                 fontweight='bold', y=1.02)

    for idx, name in enumerate(datasets):
        ax = axes[idx // cols][idx % cols]
        df = loaded_datasets[name]
        color = DATASET_COLORS.get(name, '#333')

        ax.scatter(df['gt_pct'], df['ext_pct'], alpha=0.4, s=15, c=color, edgecolors='none')

        # Identity line
        all_vals = pd.concat([df['gt_pct'], df['ext_pct']])
        vmin, vmax = all_vals.min(), all_vals.max()
        margin = (vmax - vmin) * 0.05
        ax.plot([vmin - margin, vmax + margin], [vmin - margin, vmax + margin],
                'k--', lw=1, alpha=0.6, label='Identity')

        # Compute r
        r = df['gt_pct'].corr(df['ext_pct'])
        n = len(df)
        display = DISPLAY_NAMES.get(name, name)
        ax.set_title(f'{display} (n={n}, r={r:.3f})', fontsize=11)
        ax.set_xlabel('Ground-truth effect (%)')
        ax.set_ylabel('Extracted effect (%)')

        # Add r annotation
        ax.text(0.05, 0.92, f'r = {r:.3f}', transform=ax.transAxes,
                fontsize=10, va='top',
                bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    # Hide unused axes
    for idx in range(n_panels, rows * cols):
        axes[idx // cols][idx % cols].set_visible(False)

    plt.tight_layout()
    plt.savefig(os.path.join(FIGURES_DIR, 'figure2_scatter_plots.png'))
    plt.close()
    print(f"  Saved Figure 2: Scatter plots ({n_panels} panels)")


# ---------------------------------------------------------------------------
# Figure 3: Cross-dataset comparison bar chart
# ---------------------------------------------------------------------------

def generate_figure3(formal_stats):
    """Generate Figure 3: Cross-dataset comparison bar chart."""
    if formal_stats is None:
        print("  Skipping Figure 3: no formal stats")
        return

    datasets = formal_stats.get('datasets', [])
    if not datasets:
        print("  Skipping Figure 3: empty datasets")
        return

    names = []
    r_vals = []
    mae_vals = []
    dir_vals = []

    for ds in datasets:
        short_name = ds['dataset'].split('(')[0].strip()
        if len(short_name) > 15:
            short_name = short_name[:15]
        # Use standardized display name
        short_name = DISPLAY_NAMES.get(short_name, short_name)
        names.append(short_name)
        r_vals.append(ds['pearson']['r'] if ds['pearson']['r'] else 0)
        mae_vals.append(ds['mae'] if ds['mae'] else 0)
        dir_pct = ds['direction']['pct'] if ds['direction']['pct'] else 0
        dir_vals.append(dir_pct)

    fig, axes = plt.subplots(1, 3, figsize=(14, 5))
    fig.suptitle('Figure 3: Cross-Dataset Validation Metrics', fontsize=14,
                 fontweight='bold')

    x = np.arange(len(names))
    colors = [list(DATASET_COLORS.values())[i % len(DATASET_COLORS)] for i in range(len(names))]

    # Panel A: Pearson r
    ax = axes[0]
    bars = ax.bar(x, r_vals, color=colors, edgecolor='black', linewidth=0.5)
    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=30, ha='right', fontsize=8)
    ax.set_ylabel('Pearson r')
    ax.set_title('A. Correlation')
    ax.set_ylim(0.7, 1.02)
    ax.axhline(y=0.9, color='gray', linestyle='--', alpha=0.5, label='r = 0.9')
    for i, v in enumerate(r_vals):
        ax.text(i, v + 0.005, f'{v:.3f}', ha='center', va='bottom', fontsize=8)
    ax.legend(fontsize=8)

    # Panel B: MAE
    ax = axes[1]
    ax.bar(x, mae_vals, color=colors, edgecolor='black', linewidth=0.5)
    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=30, ha='right', fontsize=8)
    ax.set_ylabel('MAE (pp)')
    ax.set_title('B. Mean Absolute Error')
    for i, v in enumerate(mae_vals):
        ax.text(i, v + 0.1, f'{v:.2f}', ha='center', va='bottom', fontsize=8)

    # Panel C: Direction agreement
    ax = axes[2]
    ax.bar(x, dir_vals, color=colors, edgecolor='black', linewidth=0.5)
    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=30, ha='right', fontsize=8)
    ax.set_ylabel('Direction Agreement (%)')
    ax.set_title('C. Direction Agreement')
    ax.set_ylim(75, 102)
    ax.axhline(y=90, color='gray', linestyle='--', alpha=0.5, label='90%')
    for i, v in enumerate(dir_vals):
        ax.text(i, v + 0.3, f'{v:.1f}%', ha='center', va='bottom', fontsize=8)
    ax.legend(fontsize=8)

    plt.tight_layout()
    plt.savefig(os.path.join(FIGURES_DIR, 'figure3_cross_dataset_comparison.png'))
    plt.close()
    print("  Saved Figure 3: Cross-dataset comparison")


# ---------------------------------------------------------------------------
# Figure 4: Bland-Altman plots
# ---------------------------------------------------------------------------

def generate_figure4(loaded_datasets, formal_stats):
    """Generate Figure 4: Bland-Altman plots (one panel per dataset)."""
    datasets_with_data = [k for k in ['Loladze', 'Hui', 'Li', 'Biochar', 'Boldorini']
                          if k in loaded_datasets]
    n_panels = len(datasets_with_data)
    if n_panels == 0:
        print("  Skipping Figure 4: no paired data")
        return

    # Get Bland-Altman stats from formal_stats if available
    ba_stats = {}
    if formal_stats:
        for ds in formal_stats.get('datasets', []):
            short = ds['dataset'].split('(')[0].strip().split()[0]
            ba = ds.get('bland_altman', {})
            if ba.get('mean_bias') is not None:
                ba_stats[short] = ba

    cols = min(n_panels, 3)
    rows = (n_panels + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(5 * cols, 5 * rows), squeeze=False)
    fig.suptitle('Figure 4: Bland-Altman Plots', fontsize=14, fontweight='bold', y=1.02)

    for idx, name in enumerate(datasets_with_data):
        ax = axes[idx // cols][idx % cols]
        df = loaded_datasets[name]
        color = DATASET_COLORS.get(name, '#333')

        diff = df['ext_pct'] - df['gt_pct']
        mean_val = (df['ext_pct'] + df['gt_pct']) / 2

        ax.scatter(mean_val, diff, alpha=0.4, s=15, c=color, edgecolors='none')

        mean_diff = diff.mean()
        sd_diff = diff.std()
        loa_upper = mean_diff + 1.96 * sd_diff
        loa_lower = mean_diff - 1.96 * sd_diff

        ax.axhline(y=mean_diff, color='black', linestyle='-', lw=1,
                   label=f'Bias = {mean_diff:.2f}')
        ax.axhline(y=loa_upper, color='red', linestyle='--', lw=1,
                   label=f'+1.96 SD = {loa_upper:.1f}')
        ax.axhline(y=loa_lower, color='red', linestyle='--', lw=1,
                   label=f'-1.96 SD = {loa_lower:.1f}')
        ax.axhline(y=0, color='gray', linestyle=':', lw=0.5)

        display = DISPLAY_NAMES.get(name, name)
        ax.set_title(f'{display} (n={len(df)})', fontsize=11)
        ax.set_xlabel('Mean of extracted and GT (%)')
        ax.set_ylabel('Difference (extracted - GT, pp)')
        ax.legend(fontsize=7, loc='upper right')

    for idx in range(n_panels, rows * cols):
        axes[idx // cols][idx % cols].set_visible(False)

    plt.tight_layout()
    plt.savefig(os.path.join(FIGURES_DIR, 'figure4_bland_altman.png'))
    plt.close()
    print(f"  Saved Figure 4: Bland-Altman plots ({n_panels} panels)")


# ---------------------------------------------------------------------------
# Figure 5: Source type accuracy comparison
# ---------------------------------------------------------------------------

def generate_figure5():
    """Generate Figure 5: Source type accuracy comparison (table vs figure)."""
    # Data from the paper and biochar analysis
    source_data = {
        'Source Type': ['Table', 'Figure'],
        'Median AE (pp)': [0.57, 3.12],
        'MAE (pp)': [0.89, 4.87],
        'Within 2pp (%)': [85, 42],
        'Within 5pp (%)': [100, 78],
    }
    df = pd.DataFrame(source_data)

    fig, axes = plt.subplots(1, 3, figsize=(13, 4.5))
    fig.suptitle('Figure 5: Extraction Accuracy by Data Source Type (Biochar Dataset)',
                 fontsize=13, fontweight='bold')

    colors_src = ['#2ca02c', '#ff7f0e']

    # Panel A: MAE comparison
    ax = axes[0]
    bars = ax.bar(['Table', 'Figure'], df['MAE (pp)'], color=colors_src,
                  edgecolor='black', linewidth=0.5)
    ax.set_ylabel('MAE (pp)')
    ax.set_title('A. Mean Absolute Error')
    for i, v in enumerate(df['MAE (pp)']):
        ax.text(i, v + 0.1, f'{v:.2f}', ha='center', va='bottom', fontsize=10)
    ax.text(0.5, 0.85, '5.5x difference', transform=ax.transAxes, ha='center',
            fontsize=10, fontstyle='italic', color='#666')

    # Panel B: Median AE
    ax = axes[1]
    ax.bar(['Table', 'Figure'], df['Median AE (pp)'], color=colors_src,
           edgecolor='black', linewidth=0.5)
    ax.set_ylabel('Median AE (pp)')
    ax.set_title('B. Median Absolute Error')
    for i, v in enumerate(df['Median AE (pp)']):
        ax.text(i, v + 0.05, f'{v:.2f}', ha='center', va='bottom', fontsize=10)

    # Panel C: Within threshold
    ax = axes[2]
    x = np.arange(2)
    width = 0.35
    bars1 = ax.bar(x - width/2, df['Within 2pp (%)'], width, label='Within 2 pp',
                   color=['#2ca02c', '#ff7f0e'], edgecolor='black', linewidth=0.5,
                   alpha=0.7)
    bars2 = ax.bar(x + width/2, df['Within 5pp (%)'], width, label='Within 5 pp',
                   color=['#2ca02c', '#ff7f0e'], edgecolor='black', linewidth=0.5,
                   alpha=1.0)
    ax.set_ylabel('Observations (%)')
    ax.set_title('C. Observations Within Threshold')
    ax.set_xticks(x)
    ax.set_xticklabels(['Table', 'Figure'])
    ax.set_ylim(0, 110)
    ax.legend(fontsize=9)
    for bar_group in [bars1, bars2]:
        for bar in bar_group:
            h = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2, h + 1, f'{h:.0f}%',
                    ha='center', va='bottom', fontsize=8)

    plt.tight_layout()
    plt.savefig(os.path.join(FIGURES_DIR, 'figure5_source_type_accuracy.png'))
    plt.close()
    print("  Saved Figure 5: Source type accuracy comparison")


# ---------------------------------------------------------------------------
# Bonus: Figure 6 -- Aggregate effect reproduction
# ---------------------------------------------------------------------------

def generate_figure6(formal_stats):
    """Generate Figure 6: Aggregate effect reproduction (GT vs extracted)."""
    if formal_stats is None:
        print("  Skipping Figure 6: no formal stats")
        return

    datasets = formal_stats.get('datasets', [])
    if not datasets:
        return

    names = []
    gt_effects = []
    ext_effects = []

    for ds in datasets:
        short_name = ds['dataset'].split('(')[0].strip()
        if len(short_name) > 15:
            short_name = short_name[:15]
        # Use standardized display name
        short_name = DISPLAY_NAMES.get(short_name, short_name)
        oe = ds.get('overall_effect', {})
        gt_mean = oe.get('gt_mean')
        ext_mean = oe.get('ext_mean')
        if gt_mean is not None and ext_mean is not None:
            names.append(short_name)
            gt_effects.append(gt_mean)
            ext_effects.append(ext_mean)

    if not names:
        return

    fig, ax = plt.subplots(figsize=(10, 5))
    x = np.arange(len(names))
    width = 0.35

    bars1 = ax.bar(x - width/2, gt_effects, width, label='Ground Truth',
                   color='#1f77b4', edgecolor='black', linewidth=0.5)
    bars2 = ax.bar(x + width/2, ext_effects, width, label='Extracted',
                   color='#ff7f0e', edgecolor='black', linewidth=0.5)

    ax.set_ylabel('Mean Effect Size (%)')
    ax.set_title('Figure 6: Aggregate Effect Size Reproduction', fontsize=13,
                 fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=30, ha='right', fontsize=9)
    ax.legend(fontsize=10)
    ax.axhline(y=0, color='gray', linestyle='-', lw=0.5)

    # Add difference annotations
    for i in range(len(names)):
        diff = abs(gt_effects[i] - ext_effects[i])
        y_pos = max(gt_effects[i], ext_effects[i])
        if y_pos < 0:
            y_pos = min(gt_effects[i], ext_effects[i]) - 1.5
        else:
            y_pos = y_pos + 1
        ax.text(i, y_pos, f'\u0394={diff:.2f} pp', ha='center', va='bottom',
                fontsize=8, color='#666')

    plt.tight_layout()
    plt.savefig(os.path.join(FIGURES_DIR, 'figure6_aggregate_effects.png'))
    plt.close()
    print("  Saved Figure 6: Aggregate effect reproduction")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Generating publication figures")
    print("=" * 60)
    print()

    print("Loading formal statistics...")
    formal_stats = load_formal_stats()
    if formal_stats:
        n_ds = formal_stats.get('n_datasets', 0)
        n_obs = formal_stats.get('total_obs', 0)
        print(f"  Found {n_ds} datasets, {n_obs} total observations")
    print()

    print("Loading paired validation data...")
    combined, loaded = load_all_matches()
    print()

    print("Generating figures...")

    # Figure 1: Architecture
    try:
        generate_figure1()
    except Exception as e:
        print(f"  ERROR generating Figure 1: {e}")

    # Figure 2: Scatter plots
    try:
        generate_figure2(loaded)
    except Exception as e:
        print(f"  ERROR generating Figure 2: {e}")

    # Figure 3: Cross-dataset comparison
    try:
        generate_figure3(formal_stats)
    except Exception as e:
        print(f"  ERROR generating Figure 3: {e}")

    # Figure 4: Bland-Altman
    try:
        generate_figure4(loaded, formal_stats)
    except Exception as e:
        print(f"  ERROR generating Figure 4: {e}")

    # Figure 5: Source type
    try:
        generate_figure5()
    except Exception as e:
        print(f"  ERROR generating Figure 5: {e}")

    # Figure 6: Aggregate effects (bonus)
    try:
        generate_figure6(formal_stats)
    except Exception as e:
        print(f"  ERROR generating Figure 6: {e}")

    print()
    print("=" * 60)
    print(f"Figures saved to: {FIGURES_DIR}")
    print("=" * 60)

    # List generated files
    if os.path.exists(FIGURES_DIR):
        files = sorted(os.listdir(FIGURES_DIR))
        for f in files:
            size = os.path.getsize(os.path.join(FIGURES_DIR, f))
            print(f"  {f} ({size:,} bytes)")


if __name__ == '__main__':
    main()
